export default {
  dataset: [
  {
    "age": 63, 
    "ca": 0, 
    "chol": 233, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 2.3, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 0, 
    "target": 1, 
    "thal": 1, 
    "thalach": 150, 
    "trestbps": 145
  },
  {
    "age": 37, 
    "ca": 0, 
    "chol": 250, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 3.5, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 0, 
    "target": 1, 
    "thal": 2, 
    "thalach": 187, 
    "trestbps": 130
  }, 
  {
    "age": 41, 
    "ca": 0, 
    "chol": 204, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.4, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 172, 
    "trestbps": 130
  }, 
  {
    "age": 56, 
    "ca": 0, 
    "chol": 236, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.8, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 178, 
    "trestbps": 120
  }, 
  {
    "age": 57, 
    "ca": 0, 
    "chol": 354, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.6, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 163, 
    "trestbps": 120
  }, 
  {
    "age": 57, 
    "ca": 0, 
    "chol": 192, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.4, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 1, 
    "thalach": 148, 
    "trestbps": 140
  }, 
  {
    "age": 56, 
    "ca": 0, 
    "chol": 294, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.3, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 153, 
    "trestbps": 140
  }, 
  {
    "age": 44, 
    "ca": 0, 
    "chol": 263, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 173, 
    "trestbps": 120
  }, 
  {
    "age": 52, 
    "ca": 0, 
    "chol": 199, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.5, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 162, 
    "trestbps": 172
  }, 
  {
    "age": 57, 
    "ca": 0, 
    "chol": 168, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.6, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 174, 
    "trestbps": 150
  }, 
  {
    "age": 54, 
    "ca": 0, 
    "chol": 239, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 160, 
    "trestbps": 140
  }, 
  {
    "age": 48, 
    "ca": 0, 
    "chol": 275, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.2, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 139, 
    "trestbps": 130
  }, 
  {
    "age": 49, 
    "ca": 0, 
    "chol": 266, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.6, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 171, 
    "trestbps": 130
  }, 
  {
    "age": 64, 
    "ca": 0, 
    "chol": 211, 
    "cp": 3, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.8, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 144, 
    "trestbps": 110
  }, 
  {
    "age": 58, 
    "ca": 0, 
    "chol": 283, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 1.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 162, 
    "trestbps": 150
  }, 
  {
    "age": 50, 
    "ca": 0, 
    "chol": 219, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.6, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 158, 
    "trestbps": 120
  }, 
  {
    "age": 58, 
    "ca": 0, 
    "chol": 340, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 172, 
    "trestbps": 120
  }, 
  {
    "age": 66, 
    "ca": 0, 
    "chol": 226, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.6, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 0, 
    "target": 1, 
    "thal": 2, 
    "thalach": 114, 
    "trestbps": 150
  }, 
  {
    "age": 43, 
    "ca": 0, 
    "chol": 247, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.5, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 171, 
    "trestbps": 150
  }, 
  {
    "age": 69, 
    "ca": 2, 
    "chol": 239, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.8, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 151, 
    "trestbps": 140
  }, 
  {
    "age": 59, 
    "ca": 0, 
    "chol": 234, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.5, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 3, 
    "thalach": 161, 
    "trestbps": 135
  }, 
  {
    "age": 44, 
    "ca": 0, 
    "chol": 233, 
    "cp": 2, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.4, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 179, 
    "trestbps": 130
  }, 
  {
    "age": 42, 
    "ca": 0, 
    "chol": 226, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 178, 
    "trestbps": 140
  }, 
  {
    "age": 61, 
    "ca": 0, 
    "chol": 243, 
    "cp": 2, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 1.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 137, 
    "trestbps": 150
  }, 
  {
    "age": 40, 
    "ca": 0, 
    "chol": 199, 
    "cp": 3, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.4, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 178, 
    "trestbps": 140
  }, 
  {
    "age": 71, 
    "ca": 2, 
    "chol": 302, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.4, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 162, 
    "trestbps": 160
  }, 
  {
    "age": 59, 
    "ca": 0, 
    "chol": 212, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 1.6, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 157, 
    "trestbps": 150
  }, 
  {
    "age": 51, 
    "ca": 0, 
    "chol": 175, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.6, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 123, 
    "trestbps": 110
  }, 
  {
    "age": 65, 
    "ca": 1, 
    "chol": 417, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.8, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 157, 
    "trestbps": 140
  }, 
  {
    "age": 53, 
    "ca": 0, 
    "chol": 197, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 1.2, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 0, 
    "target": 1, 
    "thal": 2, 
    "thalach": 152, 
    "trestbps": 130
  }, 
  {
    "age": 41, 
    "ca": 1, 
    "chol": 198, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 168, 
    "trestbps": 105
  }, 
  {
    "age": 65, 
    "ca": 0, 
    "chol": 177, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.4, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 140, 
    "trestbps": 120
  }, 
  {
    "age": 44, 
    "ca": 0, 
    "chol": 219, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 188, 
    "trestbps": 130
  }, 
  {
    "age": 54, 
    "ca": 1, 
    "chol": 273, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.5, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 0, 
    "target": 1, 
    "thal": 2, 
    "thalach": 152, 
    "trestbps": 125
  }, 
  {
    "age": 51, 
    "ca": 1, 
    "chol": 213, 
    "cp": 3, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.4, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 125, 
    "trestbps": 125
  }, 
  {
    "age": 46, 
    "ca": 0, 
    "chol": 177, 
    "cp": 2, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.4, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 0, 
    "target": 1, 
    "thal": 2, 
    "thalach": 160, 
    "trestbps": 142
  }, 
  {
    "age": 54, 
    "ca": 0, 
    "chol": 304, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 170, 
    "trestbps": 135
  }, 
  {
    "age": 54, 
    "ca": 0, 
    "chol": 232, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.6, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 165, 
    "trestbps": 150
  }, 
  {
    "age": 65, 
    "ca": 0, 
    "chol": 269, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.8, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 148, 
    "trestbps": 155
  }, 
  {
    "age": 65, 
    "ca": 0, 
    "chol": 360, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.8, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 151, 
    "trestbps": 160
  }, 
  {
    "age": 51, 
    "ca": 1, 
    "chol": 308, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.5, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 142, 
    "trestbps": 140
  }, 
  {
    "age": 48, 
    "ca": 0, 
    "chol": 245, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.2, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 180, 
    "trestbps": 130
  }, 
  {
    "age": 45, 
    "ca": 0, 
    "chol": 208, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 3.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 148, 
    "trestbps": 104
  }, 
  {
    "age": 53, 
    "ca": 0, 
    "chol": 264, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.4, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 143, 
    "trestbps": 130
  }, 
  {
    "age": 39, 
    "ca": 0, 
    "chol": 321, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 182, 
    "trestbps": 140
  }, 
  {
    "age": 52, 
    "ca": 0, 
    "chol": 325, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 172, 
    "trestbps": 120
  }, 
  {
    "age": 44, 
    "ca": 0, 
    "chol": 235, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 180, 
    "trestbps": 140
  }, 
  {
    "age": 47, 
    "ca": 0, 
    "chol": 257, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 156, 
    "trestbps": 138
  }, 
  {
    "age": 53, 
    "ca": 0, 
    "chol": 216, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 0, 
    "thalach": 115, 
    "trestbps": 128
  }, 
  {
    "age": 53, 
    "ca": 0, 
    "chol": 234, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 160, 
    "trestbps": 138
  }, 
  {
    "age": 51, 
    "ca": 0, 
    "chol": 256, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.5, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 149, 
    "trestbps": 130
  }, 
  {
    "age": 66, 
    "ca": 0, 
    "chol": 302, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.4, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 151, 
    "trestbps": 120
  }, 
  {
    "age": 62, 
    "ca": 3, 
    "chol": 231, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.8, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 3, 
    "thalach": 146, 
    "trestbps": 130
  }, 
  {
    "age": 44, 
    "ca": 0, 
    "chol": 141, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.6, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 175, 
    "trestbps": 108
  }, 
  {
    "age": 63, 
    "ca": 0, 
    "chol": 252, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 172, 
    "trestbps": 135
  }, 
  {
    "age": 52, 
    "ca": 1, 
    "chol": 201, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.8, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 158, 
    "trestbps": 134
  }, 
  {
    "age": 48, 
    "ca": 0, 
    "chol": 222, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 186, 
    "trestbps": 122
  }, 
  {
    "age": 45, 
    "ca": 0, 
    "chol": 260, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 185, 
    "trestbps": 115
  }, 
  {
    "age": 34, 
    "ca": 0, 
    "chol": 182, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 174, 
    "trestbps": 118
  }, 
  {
    "age": 57, 
    "ca": 1, 
    "chol": 303, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 159, 
    "trestbps": 128
  }, 
  {
    "age": 71, 
    "ca": 1, 
    "chol": 265, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 130, 
    "trestbps": 110
  }, 
  {
    "age": 54, 
    "ca": 0, 
    "chol": 309, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 156, 
    "trestbps": 108
  }, 
  {
    "age": 52, 
    "ca": 0, 
    "chol": 186, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 1, 
    "thalach": 190, 
    "trestbps": 118
  }, 
  {
    "age": 41, 
    "ca": 0, 
    "chol": 203, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 1, 
    "thalach": 132, 
    "trestbps": 135
  }, 
  {
    "age": 58, 
    "ca": 0, 
    "chol": 211, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 165, 
    "trestbps": 140
  }, 
  {
    "age": 35, 
    "ca": 0, 
    "chol": 183, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.4, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 182, 
    "trestbps": 138
  }, 
  {
    "age": 51, 
    "ca": 0, 
    "chol": 222, 
    "cp": 2, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 143, 
    "trestbps": 100
  }, 
  {
    "age": 45, 
    "ca": 0, 
    "chol": 234, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.6, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 175, 
    "trestbps": 130
  }, 
  {
    "age": 44, 
    "ca": 0, 
    "chol": 220, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 170, 
    "trestbps": 120
  }, 
  {
    "age": 62, 
    "ca": 0, 
    "chol": 209, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 163, 
    "trestbps": 124
  }, 
  {
    "age": 54, 
    "ca": 0, 
    "chol": 258, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.4, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 3, 
    "thalach": 147, 
    "trestbps": 120
  }, 
  {
    "age": 51, 
    "ca": 1, 
    "chol": 227, 
    "cp": 2, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 154, 
    "trestbps": 94
  }, 
  {
    "age": 29, 
    "ca": 0, 
    "chol": 204, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 202, 
    "trestbps": 130
  }, 
  {
    "age": 51, 
    "ca": 0, 
    "chol": 261, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 186, 
    "trestbps": 140
  }, 
  {
    "age": 43, 
    "ca": 0, 
    "chol": 213, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.2, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 165, 
    "trestbps": 122
  }, 
  {
    "age": 55, 
    "ca": 0, 
    "chol": 250, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.4, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 161, 
    "trestbps": 135
  }, 
  {
    "age": 51, 
    "ca": 0, 
    "chol": 245, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 2.4, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 166, 
    "trestbps": 125
  }, 
  {
    "age": 59, 
    "ca": 0, 
    "chol": 221, 
    "cp": 1, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 164, 
    "trestbps": 140
  }, 
  {
    "age": 52, 
    "ca": 0, 
    "chol": 205, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 184, 
    "trestbps": 128
  }, 
  {
    "age": 58, 
    "ca": 0, 
    "chol": 240, 
    "cp": 2, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.6, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 3, 
    "thalach": 154, 
    "trestbps": 105
  }, 
  {
    "age": 41, 
    "ca": 0, 
    "chol": 250, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 179, 
    "trestbps": 112
  }, 
  {
    "age": 45, 
    "ca": 0, 
    "chol": 308, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 170, 
    "trestbps": 128
  }, 
  {
    "age": 60, 
    "ca": 1, 
    "chol": 318, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 160, 
    "trestbps": 102
  }, 
  {
    "age": 52, 
    "ca": 0, 
    "chol": 298, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 1.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 3, 
    "thalach": 178, 
    "trestbps": 152
  }, 
  {
    "age": 42, 
    "ca": 0, 
    "chol": 265, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.6, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 122, 
    "trestbps": 102
  }, 
  {
    "age": 67, 
    "ca": 0, 
    "chol": 564, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.6, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 3, 
    "thalach": 160, 
    "trestbps": 115
  }, 
  {
    "age": 68, 
    "ca": 1, 
    "chol": 277, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 151, 
    "trestbps": 118
  }, 
  {
    "age": 46, 
    "ca": 0, 
    "chol": 197, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 156, 
    "trestbps": 101
  }, 
  {
    "age": 54, 
    "ca": 0, 
    "chol": 214, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.6, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 158, 
    "trestbps": 110
  }, 
  {
    "age": 58, 
    "ca": 0, 
    "chol": 248, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 122, 
    "trestbps": 100
  }, 
  {
    "age": 48, 
    "ca": 2, 
    "chol": 255, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 175, 
    "trestbps": 124
  }, 
  {
    "age": 57, 
    "ca": 0, 
    "chol": 207, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 168, 
    "trestbps": 132
  }, 
  {
    "age": 52, 
    "ca": 4, 
    "chol": 223, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 169, 
    "trestbps": 138
  }, 
  {
    "age": 54, 
    "ca": 1, 
    "chol": 288, 
    "cp": 1, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 159, 
    "trestbps": 132
  }, 
  {
    "age": 45, 
    "ca": 0, 
    "chol": 160, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 138, 
    "trestbps": 112
  }, 
  {
    "age": 53, 
    "ca": 0, 
    "chol": 226, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 111, 
    "trestbps": 142
  }, 
  {
    "age": 62, 
    "ca": 0, 
    "chol": 394, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 157, 
    "trestbps": 140
  }, 
  {
    "age": 52, 
    "ca": 3, 
    "chol": 233, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.1, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 147, 
    "trestbps": 108
  }, 
  {
    "age": 43, 
    "ca": 1, 
    "chol": 315, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.9, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 162, 
    "trestbps": 130
  }, 
  {
    "age": 53, 
    "ca": 3, 
    "chol": 246, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 173, 
    "trestbps": 130
  }, 
  {
    "age": 42, 
    "ca": 2, 
    "chol": 244, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.8, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 178, 
    "trestbps": 148
  }, 
  {
    "age": 59, 
    "ca": 0, 
    "chol": 270, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 4.2, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 0, 
    "target": 1, 
    "thal": 3, 
    "thalach": 145, 
    "trestbps": 178
  }, 
  {
    "age": 63, 
    "ca": 2, 
    "chol": 195, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 179, 
    "trestbps": 140
  }, 
  {
    "age": 42, 
    "ca": 0, 
    "chol": 240, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.8, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 0, 
    "target": 1, 
    "thal": 3, 
    "thalach": 194, 
    "trestbps": 120
  }, 
  {
    "age": 50, 
    "ca": 0, 
    "chol": 196, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 163, 
    "trestbps": 129
  }, 
  {
    "age": 68, 
    "ca": 0, 
    "chol": 211, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.5, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 115, 
    "trestbps": 120
  }, 
  {
    "age": 69, 
    "ca": 1, 
    "chol": 234, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.1, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 131, 
    "trestbps": 160
  }, 
  {
    "age": 45, 
    "ca": 0, 
    "chol": 236, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.2, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 152, 
    "trestbps": 138
  }, 
  {
    "age": 50, 
    "ca": 0, 
    "chol": 244, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.1, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 162, 
    "trestbps": 120
  }, 
  {
    "age": 50, 
    "ca": 0, 
    "chol": 254, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 159, 
    "trestbps": 110
  }, 
  {
    "age": 64, 
    "ca": 0, 
    "chol": 325, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 154, 
    "trestbps": 180
  }, 
  {
    "age": 57, 
    "ca": 1, 
    "chol": 126, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 173, 
    "trestbps": 150
  }, 
  {
    "age": 64, 
    "ca": 0, 
    "chol": 313, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.2, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 133, 
    "trestbps": 140
  }, 
  {
    "age": 43, 
    "ca": 0, 
    "chol": 211, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 161, 
    "trestbps": 110
  }, 
  {
    "age": 55, 
    "ca": 0, 
    "chol": 262, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 155, 
    "trestbps": 130
  }, 
  {
    "age": 37, 
    "ca": 0, 
    "chol": 215, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 170, 
    "trestbps": 120
  }, 
  {
    "age": 41, 
    "ca": 0, 
    "chol": 214, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 168, 
    "trestbps": 130
  }, 
  {
    "age": 56, 
    "ca": 0, 
    "chol": 193, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.9, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 3, 
    "thalach": 162, 
    "trestbps": 120
  }, 
  {
    "age": 46, 
    "ca": 0, 
    "chol": 204, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 172, 
    "trestbps": 105
  }, 
  {
    "age": 46, 
    "ca": 0, 
    "chol": 243, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 152, 
    "trestbps": 138
  }, 
  {
    "age": 64, 
    "ca": 2, 
    "chol": 303, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 122, 
    "trestbps": 130
  }, 
  {
    "age": 59, 
    "ca": 0, 
    "chol": 271, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 182, 
    "trestbps": 138
  }, 
  {
    "age": 41, 
    "ca": 0, 
    "chol": 268, 
    "cp": 2, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 172, 
    "trestbps": 112
  }, 
  {
    "age": 54, 
    "ca": 0, 
    "chol": 267, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 167, 
    "trestbps": 108
  }, 
  {
    "age": 39, 
    "ca": 0, 
    "chol": 199, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 179, 
    "trestbps": 94
  }, 
  {
    "age": 34, 
    "ca": 0, 
    "chol": 210, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.7, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 192, 
    "trestbps": 118
  }, 
  {
    "age": 47, 
    "ca": 0, 
    "chol": 204, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.1, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 143, 
    "trestbps": 112
  }, 
  {
    "age": 67, 
    "ca": 1, 
    "chol": 277, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 172, 
    "trestbps": 152
  }, 
  {
    "age": 52, 
    "ca": 0, 
    "chol": 196, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.1, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 169, 
    "trestbps": 136
  }, 
  {
    "age": 74, 
    "ca": 1, 
    "chol": 269, 
    "cp": 1, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.2, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 121, 
    "trestbps": 120
  }, 
  {
    "age": 54, 
    "ca": 1, 
    "chol": 201, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 163, 
    "trestbps": 160
  }, 
  {
    "age": 49, 
    "ca": 0, 
    "chol": 271, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 162, 
    "trestbps": 134
  }, 
  {
    "age": 42, 
    "ca": 0, 
    "chol": 295, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 162, 
    "trestbps": 120
  }, 
  {
    "age": 41, 
    "ca": 0, 
    "chol": 235, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 153, 
    "trestbps": 110
  }, 
  {
    "age": 41, 
    "ca": 0, 
    "chol": 306, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 163, 
    "trestbps": 126
  }, 
  {
    "age": 49, 
    "ca": 0, 
    "chol": 269, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 163, 
    "trestbps": 130
  }, 
  {
    "age": 60, 
    "ca": 0, 
    "chol": 178, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 96, 
    "trestbps": 120
  }, 
  {
    "age": 62, 
    "ca": 0, 
    "chol": 208, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 140, 
    "trestbps": 128
  }, 
  {
    "age": 57, 
    "ca": 0, 
    "chol": 201, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.5, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 1, 
    "thalach": 126, 
    "trestbps": 110
  }, 
  {
    "age": 64, 
    "ca": 1, 
    "chol": 263, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 3, 
    "thalach": 105, 
    "trestbps": 128
  }, 
  {
    "age": 51, 
    "ca": 0, 
    "chol": 295, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.6, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 157, 
    "trestbps": 120
  }, 
  {
    "age": 43, 
    "ca": 0, 
    "chol": 303, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 181, 
    "trestbps": 115
  }, 
  {
    "age": 42, 
    "ca": 0, 
    "chol": 209, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 173, 
    "trestbps": 120
  }, 
  {
    "age": 67, 
    "ca": 2, 
    "chol": 223, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.3, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 142, 
    "trestbps": 106
  }, 
  {
    "age": 76, 
    "ca": 0, 
    "chol": 197, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.1, 
    "restecg": 2, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 116, 
    "trestbps": 140
  }, 
  {
    "age": 70, 
    "ca": 0, 
    "chol": 245, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 143, 
    "trestbps": 156
  }, 
  {
    "age": 44, 
    "ca": 1, 
    "chol": 242, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.3, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 149, 
    "trestbps": 118
  }, 
  {
    "age": 60, 
    "ca": 0, 
    "chol": 240, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.9, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 171, 
    "trestbps": 150
  }, 
  {
    "age": 44, 
    "ca": 0, 
    "chol": 226, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 169, 
    "trestbps": 120
  }, 
  {
    "age": 42, 
    "ca": 0, 
    "chol": 180, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 150, 
    "trestbps": 130
  }, 
  {
    "age": 66, 
    "ca": 0, 
    "chol": 228, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.3, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 1, 
    "thalach": 138, 
    "trestbps": 160
  }, 
  {
    "age": 71, 
    "ca": 0, 
    "chol": 149, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.6, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 125, 
    "trestbps": 112
  }, 
  {
    "age": 64, 
    "ca": 0, 
    "chol": 227, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.6, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 3, 
    "thalach": 155, 
    "trestbps": 170
  }, 
  {
    "age": 66, 
    "ca": 1, 
    "chol": 278, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 152, 
    "trestbps": 146
  }, 
  {
    "age": 39, 
    "ca": 0, 
    "chol": 220, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 152, 
    "trestbps": 138
  }, 
  {
    "age": 58, 
    "ca": 0, 
    "chol": 197, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.6, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 1, 
    "thal": 2, 
    "thalach": 131, 
    "trestbps": 130
  }, 
  {
    "age": 47, 
    "ca": 0, 
    "chol": 253, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 179, 
    "trestbps": 130
  }, 
  {
    "age": 35, 
    "ca": 0, 
    "chol": 192, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 174, 
    "trestbps": 122
  }, 
  {
    "age": 58, 
    "ca": 4, 
    "chol": 220, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.4, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 1, 
    "thal": 3, 
    "thalach": 144, 
    "trestbps": 125
  }, 
  {
    "age": 56, 
    "ca": 0, 
    "chol": 221, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 3, 
    "thalach": 163, 
    "trestbps": 130
  }, 
  {
    "age": 56, 
    "ca": 0, 
    "chol": 240, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 0, 
    "target": 1, 
    "thal": 2, 
    "thalach": 169, 
    "trestbps": 120
  }, 
  {
    "age": 55, 
    "ca": 0, 
    "chol": 342, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 166, 
    "trestbps": 132
  }, 
  {
    "age": 41, 
    "ca": 0, 
    "chol": 157, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 182, 
    "trestbps": 120
  }, 
  {
    "age": 38, 
    "ca": 4, 
    "chol": 175, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 173, 
    "trestbps": 138
  }, 
  {
    "age": 38, 
    "ca": 4, 
    "chol": 175, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 1, 
    "thal": 2, 
    "thalach": 173, 
    "trestbps": 138
  }, 
  {
    "age": 67, 
    "ca": 3, 
    "chol": 286, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.5, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 108, 
    "trestbps": 160
  }, 
  {
    "age": 67, 
    "ca": 2, 
    "chol": 229, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.6, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 129, 
    "trestbps": 120
  }, 
  {
    "age": 62, 
    "ca": 2, 
    "chol": 268, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 3.6, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 0, 
    "target": 0, 
    "thal": 2, 
    "thalach": 160, 
    "trestbps": 140
  }, 
  {
    "age": 63, 
    "ca": 1, 
    "chol": 254, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.4, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 147, 
    "trestbps": 130
  }, 
  {
    "age": 53, 
    "ca": 0, 
    "chol": 203, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 3.1, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 0, 
    "target": 0, 
    "thal": 3, 
    "thalach": 155, 
    "trestbps": 140
  }, 
  {
    "age": 56, 
    "ca": 1, 
    "chol": 256, 
    "cp": 2, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 0.6, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 1, 
    "thalach": 142, 
    "trestbps": 130
  }, 
  {
    "age": 48, 
    "ca": 0, 
    "chol": 229, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 0, 
    "target": 0, 
    "thal": 3, 
    "thalach": 168, 
    "trestbps": 110
  }, 
  {
    "age": 58, 
    "ca": 0, 
    "chol": 284, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.8, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 160, 
    "trestbps": 120
  }, 
  {
    "age": 58, 
    "ca": 2, 
    "chol": 224, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 3.2, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 173, 
    "trestbps": 132
  }, 
  {
    "age": 60, 
    "ca": 2, 
    "chol": 206, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.4, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 132, 
    "trestbps": 130
  }, 
  {
    "age": 40, 
    "ca": 0, 
    "chol": 167, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 114, 
    "trestbps": 110
  }, 
  {
    "age": 60, 
    "ca": 2, 
    "chol": 230, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 1.4, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 160, 
    "trestbps": 117
  }, 
  {
    "age": 64, 
    "ca": 0, 
    "chol": 335, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 2, 
    "thalach": 158, 
    "trestbps": 140
  }, 
  {
    "age": 43, 
    "ca": 0, 
    "chol": 177, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.5, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 120, 
    "trestbps": 120
  }, 
  {
    "age": 57, 
    "ca": 1, 
    "chol": 276, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.6, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 1, 
    "thalach": 112, 
    "trestbps": 150
  }, 
  {
    "age": 55, 
    "ca": 1, 
    "chol": 353, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 132, 
    "trestbps": 132
  }, 
  {
    "age": 65, 
    "ca": 3, 
    "chol": 225, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 114, 
    "trestbps": 150
  }, 
  {
    "age": 61, 
    "ca": 0, 
    "chol": 330, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 0, 
    "thal": 2, 
    "thalach": 169, 
    "trestbps": 130
  }, 
  {
    "age": 58, 
    "ca": 1, 
    "chol": 230, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.5, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 165, 
    "trestbps": 112
  }, 
  {
    "age": 50, 
    "ca": 0, 
    "chol": 243, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.6, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 128, 
    "trestbps": 150
  }, 
  {
    "age": 44, 
    "ca": 1, 
    "chol": 290, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 2, 
    "thalach": 153, 
    "trestbps": 112
  }, 
  {
    "age": 60, 
    "ca": 1, 
    "chol": 253, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.4, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 144, 
    "trestbps": 130
  }, 
  {
    "age": 54, 
    "ca": 1, 
    "chol": 266, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.2, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 109, 
    "trestbps": 124
  }, 
  {
    "age": 50, 
    "ca": 1, 
    "chol": 233, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.6, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 163, 
    "trestbps": 140
  }, 
  {
    "age": 41, 
    "ca": 0, 
    "chol": 172, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 158, 
    "trestbps": 110
  }, 
  {
    "age": 51, 
    "ca": 0, 
    "chol": 305, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 142, 
    "trestbps": 130
  }, 
  {
    "age": 58, 
    "ca": 3, 
    "chol": 216, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.2, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 131, 
    "trestbps": 128
  }, 
  {
    "age": 54, 
    "ca": 1, 
    "chol": 188, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.4, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 113, 
    "trestbps": 120
  }, 
  {
    "age": 60, 
    "ca": 2, 
    "chol": 282, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.8, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 142, 
    "trestbps": 145
  }, 
  {
    "age": 60, 
    "ca": 0, 
    "chol": 185, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 3.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 155, 
    "trestbps": 140
  }, 
  {
    "age": 59, 
    "ca": 0, 
    "chol": 326, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 3.4, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 0, 
    "target": 0, 
    "thal": 3, 
    "thalach": 140, 
    "trestbps": 170
  }, 
  {
    "age": 46, 
    "ca": 0, 
    "chol": 231, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 3.6, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 147, 
    "trestbps": 150
  }, 
  {
    "age": 67, 
    "ca": 2, 
    "chol": 254, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 163, 
    "trestbps": 125
  }, 
  {
    "age": 62, 
    "ca": 2, 
    "chol": 267, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.8, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 99, 
    "trestbps": 120
  }, 
  {
    "age": 65, 
    "ca": 2, 
    "chol": 248, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.6, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 1, 
    "thalach": 158, 
    "trestbps": 110
  }, 
  {
    "age": 44, 
    "ca": 1, 
    "chol": 197, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 2, 
    "thalach": 177, 
    "trestbps": 110
  }, 
  {
    "age": 60, 
    "ca": 1, 
    "chol": 258, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.8, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 141, 
    "trestbps": 125
  }, 
  {
    "age": 58, 
    "ca": 0, 
    "chol": 270, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.8, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 111, 
    "trestbps": 150
  }, 
  {
    "age": 68, 
    "ca": 0, 
    "chol": 274, 
    "cp": 2, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 1.6, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 150, 
    "trestbps": 180
  }, 
  {
    "age": 62, 
    "ca": 3, 
    "chol": 164, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 6.2, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 0, 
    "target": 0, 
    "thal": 3, 
    "thalach": 145, 
    "trestbps": 160
  }, 
  {
    "age": 52, 
    "ca": 1, 
    "chol": 255, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 161, 
    "trestbps": 128
  }, 
  {
    "age": 59, 
    "ca": 1, 
    "chol": 239, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 142, 
    "trestbps": 110
  }, 
  {
    "age": 60, 
    "ca": 2, 
    "chol": 258, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.6, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 157, 
    "trestbps": 150
  }, 
  {
    "age": 49, 
    "ca": 3, 
    "chol": 188, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 139, 
    "trestbps": 120
  }, 
  {
    "age": 59, 
    "ca": 1, 
    "chol": 177, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 162, 
    "trestbps": 140
  }, 
  {
    "age": 57, 
    "ca": 1, 
    "chol": 229, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.4, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 150, 
    "trestbps": 128
  }, 
  {
    "age": 61, 
    "ca": 1, 
    "chol": 260, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 3.6, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 140, 
    "trestbps": 120
  }, 
  {
    "age": 39, 
    "ca": 0, 
    "chol": 219, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 140, 
    "trestbps": 118
  }, 
  {
    "age": 61, 
    "ca": 0, 
    "chol": 307, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 146, 
    "trestbps": 145
  }, 
  {
    "age": 56, 
    "ca": 1, 
    "chol": 249, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 1.2, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 144, 
    "trestbps": 125
  }, 
  {
    "age": 43, 
    "ca": 0, 
    "chol": 341, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 3.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 136, 
    "trestbps": 132
  }, 
  {
    "age": 62, 
    "ca": 1, 
    "chol": 263, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 97, 
    "trestbps": 130
  }, 
  {
    "age": 63, 
    "ca": 3, 
    "chol": 330, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 1.8, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 132, 
    "trestbps": 130
  }, 
  {
    "age": 65, 
    "ca": 1, 
    "chol": 254, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.8, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 127, 
    "trestbps": 135
  }, 
  {
    "age": 48, 
    "ca": 2, 
    "chol": 256, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 150, 
    "trestbps": 130
  }, 
  {
    "age": 63, 
    "ca": 3, 
    "chol": 407, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 4.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 154, 
    "trestbps": 150
  }, 
  {
    "age": 55, 
    "ca": 0, 
    "chol": 217, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 5.6, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 0, 
    "target": 0, 
    "thal": 3, 
    "thalach": 111, 
    "trestbps": 140
  }, 
  {
    "age": 65, 
    "ca": 1, 
    "chol": 282, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 1.4, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 174, 
    "trestbps": 138
  }, 
  {
    "age": 56, 
    "ca": 2, 
    "chol": 288, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 4.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 0, 
    "target": 0, 
    "thal": 3, 
    "thalach": 133, 
    "trestbps": 200
  }, 
  {
    "age": 54, 
    "ca": 1, 
    "chol": 239, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.8, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 126, 
    "trestbps": 110
  }, 
  {
    "age": 70, 
    "ca": 0, 
    "chol": 174, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.6, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 0, 
    "target": 0, 
    "thal": 3, 
    "thalach": 125, 
    "trestbps": 145
  }, 
  {
    "age": 62, 
    "ca": 1, 
    "chol": 281, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.4, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 103, 
    "trestbps": 120
  }, 
  {
    "age": 35, 
    "ca": 0, 
    "chol": 198, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.6, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 130, 
    "trestbps": 120
  }, 
  {
    "age": 59, 
    "ca": 0, 
    "chol": 288, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.2, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 159, 
    "trestbps": 170
  }, 
  {
    "age": 64, 
    "ca": 0, 
    "chol": 309, 
    "cp": 2, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.8, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 131, 
    "trestbps": 125
  }, 
  {
    "age": 47, 
    "ca": 0, 
    "chol": 243, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 2, 
    "thalach": 152, 
    "trestbps": 108
  }, 
  {
    "age": 57, 
    "ca": 3, 
    "chol": 289, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 1.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 124, 
    "trestbps": 165
  }, 
  {
    "age": 55, 
    "ca": 1, 
    "chol": 289, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.8, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 145, 
    "trestbps": 160
  }, 
  {
    "age": 64, 
    "ca": 1, 
    "chol": 246, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.2, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 0, 
    "target": 0, 
    "thal": 2, 
    "thalach": 96, 
    "trestbps": 120
  }, 
  {
    "age": 70, 
    "ca": 3, 
    "chol": 322, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.4, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 109, 
    "trestbps": 130
  }, 
  {
    "age": 51, 
    "ca": 0, 
    "chol": 299, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.6, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 173, 
    "trestbps": 140
  }, 
  {
    "age": 58, 
    "ca": 2, 
    "chol": 300, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 171, 
    "trestbps": 125
  }, 
  {
    "age": 60, 
    "ca": 2, 
    "chol": 293, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 170, 
    "trestbps": 140
  }, 
  {
    "age": 77, 
    "ca": 3, 
    "chol": 304, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 2, 
    "thalach": 162, 
    "trestbps": 125
  }, 
  {
    "age": 35, 
    "ca": 0, 
    "chol": 282, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 156, 
    "trestbps": 126
  }, 
  {
    "age": 70, 
    "ca": 1, 
    "chol": 269, 
    "cp": 2, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.9, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 112, 
    "trestbps": 160
  }, 
  {
    "age": 59, 
    "ca": 0, 
    "chol": 249, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 143, 
    "trestbps": 174
  }, 
  {
    "age": 64, 
    "ca": 2, 
    "chol": 212, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 1, 
    "thalach": 132, 
    "trestbps": 145
  }, 
  {
    "age": 57, 
    "ca": 1, 
    "chol": 274, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 88, 
    "trestbps": 152
  }, 
  {
    "age": 56, 
    "ca": 1, 
    "chol": 184, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.1, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 1, 
    "thalach": 105, 
    "trestbps": 132
  }, 
  {
    "age": 48, 
    "ca": 0, 
    "chol": 274, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.5, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 166, 
    "trestbps": 124
  }, 
  {
    "age": 56, 
    "ca": 2, 
    "chol": 409, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.9, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 150, 
    "trestbps": 134
  }, 
  {
    "age": 66, 
    "ca": 3, 
    "chol": 246, 
    "cp": 1, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 1, 
    "thalach": 120, 
    "trestbps": 160
  }, 
  {
    "age": 54, 
    "ca": 1, 
    "chol": 283, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 195, 
    "trestbps": 192
  }, 
  {
    "age": 69, 
    "ca": 3, 
    "chol": 254, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 146, 
    "trestbps": 140
  }, 
  {
    "age": 51, 
    "ca": 3, 
    "chol": 298, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 4.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 122, 
    "trestbps": 140
  }, 
  {
    "age": 43, 
    "ca": 4, 
    "chol": 247, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 0.1, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 143, 
    "trestbps": 132
  }, 
  {
    "age": 62, 
    "ca": 3, 
    "chol": 294, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 1.9, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 106, 
    "trestbps": 138
  }, 
  {
    "age": 67, 
    "ca": 2, 
    "chol": 299, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.9, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 125, 
    "trestbps": 100
  }, 
  {
    "age": 59, 
    "ca": 0, 
    "chol": 273, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 2, 
    "thalach": 125, 
    "trestbps": 160
  }, 
  {
    "age": 45, 
    "ca": 3, 
    "chol": 309, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 147, 
    "trestbps": 142
  }, 
  {
    "age": 58, 
    "ca": 2, 
    "chol": 259, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 3.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 130, 
    "trestbps": 128
  }, 
  {
    "age": 50, 
    "ca": 0, 
    "chol": 200, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.9, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 126, 
    "trestbps": 144
  }, 
  {
    "age": 62, 
    "ca": 0, 
    "chol": 244, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.4, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 154, 
    "trestbps": 150
  }, 
  {
    "age": 38, 
    "ca": 0, 
    "chol": 231, 
    "cp": 3, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 3.8, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 182, 
    "trestbps": 120
  }, 
  {
    "age": 66, 
    "ca": 2, 
    "chol": 228, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 1.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 165, 
    "trestbps": 178
  }, 
  {
    "age": 52, 
    "ca": 1, 
    "chol": 230, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 2, 
    "thalach": 160, 
    "trestbps": 112
  }, 
  {
    "age": 53, 
    "ca": 2, 
    "chol": 282, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 95, 
    "trestbps": 123
  }, 
  {
    "age": 63, 
    "ca": 2, 
    "chol": 269, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.8, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 169, 
    "trestbps": 108
  }, 
  {
    "age": 54, 
    "ca": 1, 
    "chol": 206, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 108, 
    "trestbps": 110
  }, 
  {
    "age": 66, 
    "ca": 1, 
    "chol": 212, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.1, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 2, 
    "thalach": 132, 
    "trestbps": 112
  }, 
  {
    "age": 55, 
    "ca": 0, 
    "chol": 327, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 3.4, 
    "restecg": 2, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 117, 
    "trestbps": 180
  }, 
  {
    "age": 49, 
    "ca": 3, 
    "chol": 149, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.8, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 2, 
    "thalach": 126, 
    "trestbps": 118
  }, 
  {
    "age": 54, 
    "ca": 2, 
    "chol": 286, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 3.2, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 116, 
    "trestbps": 122
  }, 
  {
    "age": 56, 
    "ca": 0, 
    "chol": 283, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 1.6, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 0, 
    "target": 0, 
    "thal": 3, 
    "thalach": 103, 
    "trestbps": 130
  }, 
  {
    "age": 46, 
    "ca": 0, 
    "chol": 249, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.8, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 144, 
    "trestbps": 120
  }, 
  {
    "age": 61, 
    "ca": 2, 
    "chol": 234, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.6, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 145, 
    "trestbps": 134
  }, 
  {
    "age": 67, 
    "ca": 0, 
    "chol": 237, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 71, 
    "trestbps": 120
  }, 
  {
    "age": 58, 
    "ca": 1, 
    "chol": 234, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.1, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 156, 
    "trestbps": 100
  }, 
  {
    "age": 47, 
    "ca": 1, 
    "chol": 275, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 118, 
    "trestbps": 110
  }, 
  {
    "age": 52, 
    "ca": 2, 
    "chol": 212, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 168, 
    "trestbps": 125
  }, 
  {
    "age": 58, 
    "ca": 1, 
    "chol": 218, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 2.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 105, 
    "trestbps": 146
  }, 
  {
    "age": 57, 
    "ca": 0, 
    "chol": 261, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.3, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 141, 
    "trestbps": 124
  }, 
  {
    "age": 58, 
    "ca": 2, 
    "chol": 319, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 2, 
    "target": 0, 
    "thal": 2, 
    "thalach": 152, 
    "trestbps": 136
  }, 
  {
    "age": 61, 
    "ca": 1, 
    "chol": 166, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 3.6, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 125, 
    "trestbps": 138
  }, 
  {
    "age": 42, 
    "ca": 0, 
    "chol": 315, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.8, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 1, 
    "thalach": 125, 
    "trestbps": 136
  }, 
  {
    "age": 52, 
    "ca": 0, 
    "chol": 204, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 1.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 0, 
    "thalach": 156, 
    "trestbps": 128
  }, 
  {
    "age": 59, 
    "ca": 1, 
    "chol": 218, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 2.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 1, 
    "thalach": 134, 
    "trestbps": 126
  }, 
  {
    "age": 40, 
    "ca": 0, 
    "chol": 223, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 181, 
    "trestbps": 152
  }, 
  {
    "age": 61, 
    "ca": 1, 
    "chol": 207, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.9, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 138, 
    "trestbps": 140
  }, 
  {
    "age": 46, 
    "ca": 2, 
    "chol": 311, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.8, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 120, 
    "trestbps": 140
  }, 
  {
    "age": 59, 
    "ca": 2, 
    "chol": 204, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.8, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 2, 
    "thalach": 162, 
    "trestbps": 134
  }, 
  {
    "age": 57, 
    "ca": 1, 
    "chol": 232, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 2, 
    "thalach": 164, 
    "trestbps": 154
  }, 
  {
    "age": 57, 
    "ca": 1, 
    "chol": 335, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 3.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 143, 
    "trestbps": 110
  }, 
  {
    "age": 55, 
    "ca": 1, 
    "chol": 205, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.0, 
    "restecg": 2, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 130, 
    "trestbps": 128
  }, 
  {
    "age": 61, 
    "ca": 1, 
    "chol": 203, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 161, 
    "trestbps": 148
  }, 
  {
    "age": 58, 
    "ca": 3, 
    "chol": 318, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 4.4, 
    "restecg": 2, 
    "sex": 1, 
    "slope": 0, 
    "target": 0, 
    "thal": 1, 
    "thalach": 140, 
    "trestbps": 114
  }, 
  {
    "age": 58, 
    "ca": 2, 
    "chol": 225, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 1, 
    "oldpeak": 2.8, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 1, 
    "thalach": 146, 
    "trestbps": 170
  }, 
  {
    "age": 67, 
    "ca": 0, 
    "chol": 212, 
    "cp": 2, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.8, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 150, 
    "trestbps": 152
  }, 
  {
    "age": 44, 
    "ca": 0, 
    "chol": 169, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 2.8, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 0, 
    "target": 0, 
    "thal": 1, 
    "thalach": 144, 
    "trestbps": 120
  }, 
  {
    "age": 63, 
    "ca": 2, 
    "chol": 187, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 4.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 2, 
    "target": 0, 
    "thal": 3, 
    "thalach": 144, 
    "trestbps": 140
  }, 
  {
    "age": 63, 
    "ca": 0, 
    "chol": 197, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 136, 
    "trestbps": 124
  }, 
  {
    "age": 59, 
    "ca": 2, 
    "chol": 176, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 1.0, 
    "restecg": 0, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 1, 
    "thalach": 90, 
    "trestbps": 164
  }, 
  {
    "age": 57, 
    "ca": 0, 
    "chol": 241, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 0.2, 
    "restecg": 1, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 123, 
    "trestbps": 140
  }, 
  {
    "age": 45, 
    "ca": 0, 
    "chol": 264, 
    "cp": 3, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 132, 
    "trestbps": 110
  }, 
  {
    "age": 68, 
    "ca": 2, 
    "chol": 193, 
    "cp": 0, 
    "exang": 0, 
    "fbs": 1, 
    "oldpeak": 3.4, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 141, 
    "trestbps": 144
  }, 
  {
    "age": 57, 
    "ca": 1, 
    "chol": 131, 
    "cp": 0, 
    "exang": 1, 
    "fbs": 0, 
    "oldpeak": 1.2, 
    "restecg": 1, 
    "sex": 1, 
    "slope": 1, 
    "target": 0, 
    "thal": 3, 
    "thalach": 115, 
    "trestbps": 130
  }, 
  {
    "age": 57, 
    "ca": 1, 
    "chol": 236, 
    "cp": 1, 
    "exang": 0, 
    "fbs": 0, 
    "oldpeak": 0.0, 
    "restecg": 0, 
    "sex": 0, 
    "slope": 1, 
    "target": 0, 
    "thal": 2, 
    "thalach": 174, 
    "trestbps": 130
  }
]}